### ISSUE TITLE
Doesn't respect UV islands

### ISSUE THREAD

**Issue by Etrusan** [gonzalo-lb/blender-uvrandomizer#1]
While great for individual faces, it doesn't respect UV islands while manipulating. Workaround could be to select individual faces from those islands, move them, pin them and then unwrap again, but that is very cumbersome (especially when you have a lot of islands). Any chance for a fix? Thanks.

**Comment by PabloMzGa** [comment]
Just discovered the addon and I think the same. Also, in Blender 3.1. an error occurs:

Python: Traceback (most recent call last):
  File "C:\Users\Username\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\UV Randomizer v0_9-3.py", line 235, in execute
    bmesh.update_edit_mesh(me, True)
TypeError: update_edit_mesh() takes at most 1 positional argument (2 given)

location: <unknown location>:-1

**Comment by gonzalo-lb** [comment]
Hi. I've commited a new version (v.1.00) It has an option that keeps the UV Islands intact (at least on Translate/Rotate/Scale functionality) and it should work both in Blender 2.9 and 3 or higher. Please let me know if something doesn't work. Thank you for the feedback.

**Comment by Etrusan** [comment]
Works great on 2.93LTS even outside of 0/1 and with pinned faces. Thanks for the update.
